### ISSUE TITLE
Support custom EVM chains

### ISSUE THREAD

**Issue by oed** [eternalsafe/wallet#23] opened 2024-12-16 14:08 UTC
## What is the feature about
Currently eternal safe can only be used with a specific list of chains. It should be possible to work with a non-listed EVM chain as long as you provide a custom RPC endpoint.

## The list of requirements
- Support adding of custom chains by setting a chain-id and rpc-url.
- Nice to have: pass custom rpc providers in links, e.g. `https://eternalsafe.eth.link?rpc=<url>&chain-id=234`

**Comment by devanoneth** [comment] 2024-12-22 10:04
Thanks for the suggestion! Closing as duplicate of https://github.com/eternalsafe/wallet/issues/3

**Closed as completed by devanoneth** 2024-12-22 10:04 UTC
Labels: enhancement
